# Generated by Django 4.0.6 on 2022-07-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='second_name',
        ),
    ]
