# Generated by Django 4.0.6 on 2022-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_alter_profilefeeditem_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
