# Generated by Django 4.0.6 on 2022-07-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_alter_profilefeeditem_status_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='demofeedprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
